(herald "Basic password-based authentication over TLS 1.2")

(include "TLS1.2_macros.lisp") ; 4 message exchange by combining TLS messages.

(defprotocol baseline-nouaf-tls12 basic
  ;; Client roles.
  (defrole client
    (vars
      (username server ca name)
      (cr sr random32) ;; TLS nonces. cr: client random, sr: server random
      (pms random48) ;; TLS pre-master secret generated by the client.
      (pw password) 
    )
    (trace
      (TLS send recv pms cr sr server ca)
      (send (enc username pw (ClientWriteKey (MasterSecret pms cr sr))))
      (recv (enc "auth success" (ServerWriteKey (MasterSecret pms cr sr))))
    )
  )
  ;; Server roles.
  (defrole server
    (vars
      (username server ca name)
      (cr sr random32) ;; TLS nonces. cr: client random, sr: server random
      (pms random48) ;; TLS pre-master secret generated by the client.
      (pw password) 
    )
    (trace
      (TLS recv send pms cr sr server ca)
      (recv (enc username pw (ClientWriteKey (MasterSecret pms cr sr))))
      (send (enc "auth success" (ServerWriteKey (MasterSecret pms cr sr))))
    )
  )
  ;; Custom sorts.
  (lang
    (random32 atom)
    (random48 atom)
    (password atom)
  )
)

;; Client perspective skeleton.
(defskeleton baseline-nouaf-tls12
  (vars
    (server ca name)
    (cr sr random32)
    (pms random48)
    (pw password)
  )
  (defstrandmax client
    (server server) (ca ca) (cr cr) (pms pms) (sr sr) (pw pw))
  (non-orig (privk ca) (privk server))
  (uniq-orig cr pms)
  (uniq-orig sr) ;; Prevents multiple instances of the same server interacting with the client.
  (pen-non-orig pw)
)

;; Server perspective skeleton.
(defskeleton baseline-nouaf-tls12
  (vars
    (server ca name)
    (sr random32)
    (pw password)
  )
  (defstrandmax server
    (server server) (ca ca) (sr sr) (pw pw))
  (non-orig (privk ca) (privk server))
  (uniq-orig sr)
  (pen-non-orig pw)
)